name = "InterProcessCommunication"
uuid = "a7427343-1d15-5490-a218-bfcb7db836a2"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.1.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
